version: "3.9"
services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: "ylabDb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pswd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ylabdb-data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  ylabdb-data: